// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ToDoList
{
	public partial class NewItemViewController : UIViewController
	{
        /// <summary>
        /// Reference to the previous view controller (the table view controller)
        /// </summary>
        public ToDoListTableViewController TableViewController { get; set; }

		public NewItemViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        partial void addButtonClicked(NSObject sender)
        {
            if (!string.IsNullOrEmpty(nameTextField.Text))
            {
                var newItem = new ToDoItem
                {
                    Name = nameTextField.Text,
                    Important = importantSwitch.On
                };

                // Add and reload the data in the table.
                TableViewController?.ToDoItems.Add(newItem);
                TableViewController?.TableView.ReloadData();

                // After adding the view pop back to the main controller
                NavigationController.PopViewController(true);
            }
        }
    }
}
