// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ToDoList
{
	public partial class NewItemViewController : UIViewController
	{
		public NewItemViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            
        }

        partial void addButtonClicked(NSObject sender)
        {

            if (!string.IsNullOrEmpty(nameTextField.Text))
            {
                var newItem = new ToDoItem
                {
                    Name = nameTextField.Text,
                    Important = importantSwitch.On
                };
            }
        }


    }
}
