// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ToDoList
{
	public partial class ToDoListTableViewController : UITableViewController
	{
		public ToDoListTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
