// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ToDoList
{
	public partial class ToDoListTableViewController : UITableViewController
	{
		public ToDoListTableViewController (IntPtr handle) : base (handle)
		{
		}

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return 5;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
			var cell = new UITableViewCell();
			cell.TextLabel.Text = "New cell!";
			return cell;
        }
    }
}
