// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using Foundation;
using UIKit;

namespace ToDoList
{
	public partial class ToDoListTableViewController : UITableViewController
	{
        List<ToDoItem> _listItems = new List<ToDoItem>();

		public ToDoListTableViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            _listItems.Add(new ToDoItem { Important = true, Name = "Buy Milk" });
            _listItems.Add(new ToDoItem { Important = false, Name = "Walk the dog" });
        }

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return _listItems.Count;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
			var cell = new UITableViewCell();
            cell.TextLabel.Text = _listItems[indexPath.Row].Name;
			return cell;
        }
    }
}
