// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ToDoList
{
	public partial class UpdateItemViewController : UIViewController
	{
		/// <summary>
        /// The item being displayed on this controller.
        /// </summary>
		public ToDoItem Item { get; set; }

        /// <summary>
        /// Reference to the previous view controller (the table view controller)
        /// </summary>
        public ToDoListTableViewController TableViewController { get; set; }

        private ApplicationDatabase _database;

        public UpdateItemViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            if (Item != null)
            {
                nameLabel.Text = Item.Name + (Item.Important ? " (!)" : string.Empty);
            }

            _database = new ApplicationDatabase();
        }

        /// <summary>
        /// Handler for the complete button being tapped. Removes the
        /// item from the database and returns back to the list controller.
        /// </summary>
        /// <param name="sender"></param>
        partial void completeClicked(NSObject sender)
        {
            if (Item != null)
            {
                _database.Delete(Item);
                TableViewController.ReloadItems();
                NavigationController.PopViewController(true);
            }
        }
            
    }
}
